version: '3.7'
services:
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lxkdgfnbljkdhb  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
      - PUID=1020
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/pool_alpha/vm_storage/seafile/mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - net
    deploy:
      labels:
        - traefik.enable=false
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - net
    deploy:
      labels:
        - traefik.enable=false
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: seafile-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - PUID=1020
      - PGID=1000
      - TZ=America/New_York
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 2g
    volumes:
      - /mnt/pool_alpha/vm_storage/seafile/elasticsearch/data:/usr/share/elasticsearch/data  # Requested, specifies the path to Elasticsearch data persistent store.
    networks:
      - net
    deploy:
      labels:
        - traefik.enable=false
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
          
  seafile:
    image: docker.seafile.top/seafileltd/seafile-pro-mc:latest
    container_name: seafile
#  ports:
#      - "80:80"
#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /mnt/pool_alpha/vm_storage/seafile/data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=pasteinfromabove  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=America/New_York # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=seafile@mydomain.com # Specifies Seafile admin user, default is 'me@example.com'
      - SEAFILE_ADMIN_PASSWORD=crazypoassword     # Specifies Seafile admin password, default is 'asecret'
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not
      - SEAFILE_SERVER_HOSTNAME=seafile.mydomain.com # Specifies your host name if https is enabled
      - PUID=1020
      - PGID=1000
      - TZ=America/New_York
    depends_on:
      - db
      - memcached
      - elasticsearch
    networks:
      - net
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.seafile-http.rule=Host(`seafile.mydomain.com`)
        - traefik.http.routers.seafile-http.entrypoints=http
        - traefik.http.routers.seafile-http.middlewares=https-redirect
        - traefik.http.routers.seafile-https.rule=Host(`seafile.mydomain.com`)
        - traefik.http.routers.seafile-https.entrypoints=https
        - traefik.http.routers.seafile-https.tls=true
        - traefik.http.routers.seafile-https.tls.certresolver=le
        - traefik.http.services.seafile.loadbalancer.server.port=80

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

    
